### ISSUE TITLE
[Question] Rationale Behind `Clippy.toml` and `type-complexity-threshold = 5000`

### ISSUE THREAD

**Issue by zicklag** [Leafwing-Studios/template-repo#33]
Hey there, this is just a question, I was fixing Bevy clippy lints for a project and I was curious about the decision to use the Clippy.toml and `type-complexity-threshold = 5000` instead of just allowing `clippy::type_complexity`. Is there an advantage to setting it so high and not just allowing it?

This is low priority question so get to this whenever you can. :)

**Comment by alice-i-cecile** [comment]
IIRC this worked better in CI, because it would be read there? I don't remember now!
